fourth-wall.css

It looks nicer and it's easier to scan if it's not wrapped.

Prevent wrapping of the elapsed time

---

README.markdown

It was showing the build against `gh-pages`, not master.

Fix the build button, which was showing "unknown"

---

README.markdown
fourth-wall.css
fourth-wall.js

- In the Core Team we have around fifty repos to keep track of pull requests on, but only nine or ten contributors directly in the team. To avoid everyone's PRs for every one of those repos coming up and
us struggling to scan the list to find relevant ones, we've added handling for a configurable `users` file optionally included in the gist. Using CSS, we've hidden PRs from users we don't care about.
- Test gist available at: https://gist.github.com/issyl0/70cf0c8f3d0b1ccd2f6e.
- We (@alicebartlett and I) didn't do this in the BackboneJS "way". Instead we put a global `users` array at the top of the file, but it was the way that we found that worked.

Add the ability to specify users to show PRs from, through the gist

---

README.markdown

- Thanks to Matt Bostock in
https://github.com/alphagov/fourth-wall/issues/13 for suggesting
this. I hope the link will keep working, given I commented on that
Issue with an image and it uploaded it, and I'm using that same URL
to save hosting it elsewhere...

Add a screenshot of Fourth Wall to the README

---

fourth-wall.css
javascript/pull-view.js

If people are assigning themselves to pull requests as they are reviewing them, it's useful to colour the bar differently, and indicate who the assignee is.
This seems like the kind of feature that might usually live behind a toggle, but I wasn't entirely sure how that was usually done.

Add and colour assignees

---

javascript/fetch-repos.js

This had a couple of issues, 1 per commit, so thats the best way to review.
1/ Match on team slug, not name. The teams using this so far have names that are the same as their slug, but wasn't working for the custom formats team.
2/ Fetch more teams when mapping a team slug to ID, as the teams API call is paginated, and the custom formats team wasn't on the first page, and wasn't found.

Improved listing repos by github team

---

javascript/core.js
javascript/fetch-repos.js

By default the github API returns 30 items for a paginated set of
results. The repo list is paginated and on a team with more than
30 repos not all repos were shown
GH lets you request larger page sizes, up to 100, which won't
solve the problem forever, but makes it less likely we'll miss
repos when using team-based config.
:gift: **bonus refactor** :gift:: 
Support jQuery `data` option for query  parameters through 
`fetchDefer`.

Fetch as many repos for a team as possible 

---

README.markdown
javascript/core.js
javascript/fetch-repos.js
javascript/pull-view.js

A follow up to https://github.com/alphagov/fourth-wall/pull/38.
It switches the default, so filtering users is an opt in. This is a default
that encourages better behaviour, and few teams are actually using
it, so it should be the least disruptive.
(There used to be two commits, i accidentally smushed them, and it's 
too late in the day to be unpicking them  ¯\_(ツ)_/¯)
Currently you can set a list of users in the Gist configuration
and only show PRs owned by those users. This is generally used to
limit PRs to members of a single team where they share repos with
other teams and want to focus on their changes.
To switch between filtering and not you need to edit the gist,
which is more involved than a query param, especially as you
normally want the same repo list / styling / etc. …

Make filtering by user opt-in by param (+ for teams)

---

README.markdown
fourth-wall.css
javascript/fetch-repos.js
javascript/pull-view.js
javascript/pulls.js
javascript/repo.js

This is for use in conjunction with the "filterusers" parameter, to make
PRs on some repositories always be shown, even if not opened by one of
the specified users.
This allows us to have a wall which lists any PRs on repositories
"owned" by our team, together with any PRs on other repositories made by
team members.

Add support for marking repositories as important

---

README.markdown
javascript/core.js
spec/spec.fourth-wall.js

This adds support for array parameters in the URL so that it's possible to specify multiple teams for a given github instance (eg teams from 2 different github orgs).

Support multiple teams for a github instance.

---

fourth-wall.css
index.html
javascript/core.js
javascript/list-items.js
javascript/pull-view.js
javascript/pull.js
javascript/review-comment.js
spec/index.html
spec/spec.fourth-wall.js

Currently fourth wall only turns a PR green if a normal comment has a thumbs up. Github now has review comments, which are different. 
In a review you can mark the PR as approved. This PR adds a new backbone model which checks review comments for the `APPROVED` state. If found the `thumbsup` class is added to the pull-view, in the same way that is done for a normal comment with a thumbup.

Look at review comments for approval

---

README.markdown
fourth-wall.css
javascript/core.js
javascript/pull-view.js

In order to prevent WIP PRs taking up lots of space on a board, thereby
reducing the amount of space for PRs ready for review, this adds an
option to have them show only the repo, and title lines on a single
line. It also sets the background colour to dark grey to de-emphasise
them a bit.
Before:
After:

Reduce space taken by WIP PRs.

---

javascript/fetch-repos.js
javascript/master-status.js
javascript/repo.js

For some repos, the default branch is set to something other than
"master". This updates the master status tracking functionality to track
whatever the default branch is set to in Github instead of being hardcoded to
"master".
This is only supported when fetching repos by team at the moment as
that's currently the only part of the code that fetches the repo
information from Github - the gist and file methods get all the repo data
they need from the JSON data in the files.

Monitor default branch instead of master

---

README.markdown
javascript/pull-view.js

* Added 'hide' option to `wiphandling` query parameter which will $.hide() any WIP PRs. Edited: _javascript/pull-view.js_
* Updated Readme accordingly. Edited: _readme.markdown_

Added 'hide' as an option for wiphandling parameter

---

README.markdown
javascript/core.js

In the GOV.UK Pay team, people are forever putting “REVIEW ONLY” in the title of their PRs then getting sad when Fourth Wall doesn’t treat them as WIP PRs.
Usually someone will remind them in Slack to use “WIP” or “DO NOT MERGE” instead. But old habits die hard and they forget by the next time and create another “REVIEW ONLY” PR.
The end result is that a large portion of our Slack chatter is team members schooling their colleagues on how to tag WIP PRs correctly. It’s got to the point now where we’re considering writing a Slack bot to do the chastising for us.
This fixes the problem forever by treating “REVIEW ONLY” the same as  “WIP” and “DO NOT MERGE”.

Treat PRs with a “REVIEW ONLY” tag in the title as WIP PRs

---

.gitignore
README.markdown
javascript/core.js
javascript/fetch-repos.js

Some GDS repos are linked to a large number of teams,
and thus show up on all those teams' fourth walls e.g.
`gds-tech-learning-pathway`. This commit adds functionality
to enable filtering of displayed repos using a comma separated
query param, to allow teams to only see repos they are
actively concerned with.
Usage:
`https://alphagov.github.io/fourth-wall/?token=my-big-token&team=alphagov/my-big-team&fiteredrepos=my-undesired-repo-1,my-undesired-repo-2`
I would have written some tests, but have neither time nor guile
enough to figure out how to run them. There's no guidance on this,
and no package.json to manage test dependencies. So trust me, this works.
Alternatively, check it locally before approving.

Add ability to filter displayed repos

---

javascript/comment.js
javascript/list-items.js
javascript/pull-view.js

The use of thumbs-up to indicate approval of a pull request predates [Github’s own pull request review functionality](https://help.github.com/articles/about-pull-request-reviews/).
We should stop using a comment containing 👍 to indicate approval because:
- Github pull request reviews are more discoverable – there’s no special syntax to learn
- using a 👍 is ambiguous for someone not using the Fourth Wall tool
- there might be a time when you want to use a 👍 _without_ implicitly approving the whole pull request

Stop treating 👍 as approval

---

README.markdown
javascript/preflight.js

HTTP logic was broken (mb)
If someone wants to give their token access to private repos they can now do so using `extra_scopes` query param (comma separated) (e.g. `&extra_scopes=repo`).
Related to @edds comment on #59

Fix HTTP logic and add ability to accept extra scopes.

---

fourth-wall.css
index.html
index.js
javascript/connectivity.js

Commit message
--
```
Fixes #68
When a dashboard is offline then we cannot check the status of PRs. This
is unideal.
solo @tlwr
```
What
--
Adds a connectivity indicator using emoji and `navigator.onLine`
Why
--
So we are easily able to see when our dashboards aren't able to reflect reality
---
See #68

Add connectivity check

---

README.markdown

To save others from having to read the source and experiment to understand how to use the `file` parameter.

Add some documentation about how the `file` parameter works

---

javascript/preflight.js

GitHub has deprecated passing the API token as a query parameter on requests.
Provide it via an HTTP header instead.
https://trello.com/c/Avv9sRJv/334-govwifi-support9662-github-api-deprecation-notice-for-authentication-via-url-query-parameters

Avv9sRJv: Fix GitHub deprecation warning

---

javascript/preflight.js

https://trello.com/c/OS5OSEVl/144-1-decide-whether-to-migrate-shared-repos-to-ccs
We recently discovered that the Digital Marketplace team was responsible for this repo. We don't have the time or expertise to fix the [accessibility issues](https://github.com/alphagov/fourth-wall/issues/133), and we're moving to CCS soon. We asked, and no other team in GDS/CDIO wanted to take it on. So we're going to retire it in an orderly fashion.
3 weeks is probably long enough for people to notice. They'll be able to find something else, or let us know if they want to take it on to stop the retirement. Otherwise, we'll switch it off after that date.
Thanks to @abersager who created this, @lfdebrux who's been maintaining it for the past year, and [everyone …

Warn users about retirement on 22 September
